#durid登陆账号密码
loginPassword: 123456
loginUsername: root
## Mybatis 配置（持久层框架自己选择）
mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.xiaobudiankeji.base.entity
## 数据源配置
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        # 下面为连接池的补充设置，应用到上面所有数据源中
        initialSize: 5
        logSlowSql: true
        maxActive: 20
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minIdle: 5
        password: 123456
        testOnBorrow: false
        testOnReturn: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,防止sql注入
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/zuoqing?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        validationQuery: SELECT 1 FROM DUAL
