
## Mybatis 配置（持久层框架自己选择）
mybatis:
  config: classpath:mybatis-config.xml
  master:
    mapperLocations: classpath*:mapper/master/*.xml
    basePackage: com.qhh.bank.mapper
  salver:
    mapperLocations: classpath*:mapper/salver/*.xml
    basePackage: com.qhh.bank.mapper

logback:
  #非开发环境是否开启控制台日志
  enableConsoleLogWhenNotInDev: false
  #**日志文件存放目录，目录后面无需再加"/"。备注如果这项不配置，则不输出日志文件
  logFileDir: /acc-Log

## 数据源配置
spring:
  active:
    profile: dev
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initialSize: 5
      logSlowSql: true
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minIdle: 5
      password: root
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,防止sql注入
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
    salver:
      driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initialSize: 5
      logSlowSql: true
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minIdle: 5
      password: root
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,防止sql注入
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
logging:
#  config: logback.xml
  level:
    com.qhh.bank: debug
server:
  port: 8080
